import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import Banner from "../components/shared/Banner";
import Library from "../components/shared/Library";
import Footer from "@/components/shared/Footer";
import WorkProvider from "@/context/WorkContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[#05070d] min-h-screen">

        <WorkProvider>

        <Navbar></Navbar>
        
        {children}
        
        <Footer></Footer>
        </WorkProvider>

    <ToastContainer /> 

        </body>
    </html>
  );
}
